# Generated by Django 5.0.3 on 2024-04-04 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='role',
            field=models.IntegerField(choices=[(0, "Regular - Can't delete members"), (1, 'Admin - Can delete members')], default=0, max_length=1),
        ),
    ]
