# Generated by Django 5.0.3 on 2024-04-07 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_members', '0002_member_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='phone_number',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.IntegerField(choices=[(0, "Regular - Can't delete members"), (1, 'Admin - Can delete members')], default=0),
        ),
    ]
