name: Rotate Mailgun Keys

on:
  workflow_dispatch:
    inputs:
      cluster:
        description: 'Cluster to rotate keys for'
        required: true
        type: choice
        options:
          - "us-1-west.mertslounge.ca"
          - "master.gladly.qa"
          - "staging.gladly.qa"
          - "scaletest.gladly.qa"
          - "gladly.gladly.qa"
          - "production1.gladly.com"
      image-tag:
        description: 'Docker Image Tag'
        required: true
        type: string
      dry-run:
        description: 'Dry run?'
        required: true
        type: choice
        options:
          - "true"
          - "false"
      mailgun-api-key:
        description: 'Mailgun API Key'
        required: true
        type: string
      mailgun-webhook-signing-key:
        description: 'Mailgun HTTP Webhook Signing Key'
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  run-job-kubernetes:
    runs-on: ubuntu-latest

    env:
      JOB_KUBERNETES_APP: "supernova-rotate-mailgun-keys"
      KUBERNETES_RESOURCE_PATH: "tasks/kubernetes"

    steps:
      - name: Mask secret keys
        run: |
             mailgun_api_key="$(jq -r '.inputs."mailgun-api-key"' "$GITHUB_EVENT_PATH")"
             mailgun_signing_key="$(jq -r '.inputs."mailgun-webhook-signing-key"' "$GITHUB_EVENT_PATH")"
             echo "::add-mask::${mailgun_api_key}"          # Mask secrets in logs
             echo "::add-mask::${mailgun_signing_key}"

      - name: Test
        env:
          API_SECRET: ${{ inputs.mailgun-api-key }}
          SIGNING_KEY: ${{ inputs.mailgun-webhook-signing-key }}

        run: |
          echo "${{ inputs.mailgun-api-key }}"
          cat "$GITHUB_EVENT_PATH"
          cp "$GITHUB_EVENT_PATH" /tmp/event.json

      - name: Print Event File
        run: cat /tmp/event.json
