name: Rotate Mailgun Keys

on:
  workflow_dispatch:
    inputs:
      cluster:
        description: 'Cluster to rotate keys for'
        required: true
        type: choice
        options:
          - "us-1-west.mertslounge.ca"
          - "master.gladly.qa"
          - "staging.gladly.qa"
          - "scaletest.gladly.qa"
          - "gladly.gladly.qa"
          - "production1.gladly.com"
      image-tag:
        description: 'Docker Image Tag'
        required: true
        type: string
      dry-run:
        description: 'Dry run?'
        required: true
        type: choice
        options:
          - "true"
          - "false"
      mailgun-api-key:
        description: 'Mailgun API Key'
        required: true
        type: string
      mailgun-webhook-signing-key:
        description: 'Mailgun HTTP Webhook Signing Key'
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  run-job-kubernetes:
    runs-on: ubuntu-latest

    env:
      JOB_KUBERNETES_APP: "supernova-rotate-mailgun-keys"
      KUBERNETES_RESOURCE_PATH: "tasks/kubernetes"

    steps:
      - name: Mask secret values
        run: |
          mailgun_api_key="$(jq -r '.inputs."mailgun-api-key"' "$GITHUB_EVENT_PATH")"
          mailgun_signing_key="$(jq -r '.inputs."mailgun-webhook-signing-key"' "$GITHUB_EVENT_PATH")"

          echo "::add-mask::${mailgun_api_key}"
          echo "::add-mask::${mailgun_signing_key}"

          # Export to environment variables for later steps
          echo "MAILGUN_API_KEY=$mailgun_api_key" >> $GITHUB_ENV
          echo "MAILGUN_SIGNING_KEY=$mailgun_signing_key" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Substitute Environment Variables in Manifest
        run: |
          sed -i "
            s|\${IMAGE_TAG}|${{ inputs.image-tag }}|g;
            s|\${DRY_RUN}|${{ inputs.dry-run }}|g;
            s|\${MAILGUN_API_KEY}|${{ env.MAILGUN_API_KEY }}|g;
            s|\${MAILGUN_SIGNING_KEY}|${{ env.MAILGUN_SIGNING_KEY }}|g
          " ${{ env.KUBERNETES_RESOURCE_PATH }}/${{ env.JOB_KUBERNETES_APP }}-job.yml
